[package]
name = "agent"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
chrono = { version = "0.4.45", features = ["serde"] }
futures = "0.3.34"
llm = { version = "0.1.0", path = "../llm" }
mcp-client = { version = "0.1.0", path = "../mcp-client" }
serde.workspace = true
serde_json.workspace = true
serde_yaml_ng = "0.10.0"
tokio.workspace = true
tracing.workspace = true
